"""empty message

Revision ID: 93c1fe28d91f
Revises: 8fb2eb3ed4c3
Create Date: 2017-10-14 21:11:04.769179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c1fe28d91f'
down_revision = '8fb2eb3ed4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legislation_file', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('legislation_file')

    # ### end Alembic commands ###
