"""empty message

Revision ID: 957ebc2de618
Revises: 2b8b81bc427f
Create Date: 2017-09-10 02:29:54.904047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957ebc2de618'
down_revision = '2b8b81bc427f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_pw_update', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('force_pw_update')

    # ### end Alembic commands ###
