"""empty message

Revision ID: b112637fe261
Revises: 
Create Date: 2017-09-03 23:10:37.885052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b112637fe261'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant', sa.Column('owed_money_email_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grant', 'owed_money_email_date')
    # ### end Alembic commands ###
