"""empty message

Revision ID: de948ef6929a
Revises: 93c1fe28d91f
Create Date: 2017-10-14 22:20:09.308894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de948ef6929a'
down_revision = '93c1fe28d91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legislation_number', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('legislation_number')

    # ### end Alembic commands ###
