"""empty message

Revision ID: e645ddac7dad
Revises: 957ebc2de618
Create Date: 2017-09-10 12:56:06.363056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e645ddac7dad'
down_revision = '957ebc2de618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hearing_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hearing_occurred', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hearing_requested', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_column('hearing_requested')
        batch_op.drop_column('hearing_occurred')
        batch_op.drop_column('hearing_date')

    # ### end Alembic commands ###
