"""empty message

Revision ID: f489b05224c6
Revises: f79b08cd4ae1
Create Date: 2017-09-04 00:41:55.824877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f489b05224c6'
down_revision = 'f79b08cd4ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipts_due', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_column('receipts_due')

    # ### end Alembic commands ###
