"""empty message

Revision ID: f79b08cd4ae1
Revises: b112637fe261
Create Date: 2017-09-04 00:41:01.148194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79b08cd4ae1'
down_revision = 'b112637fe261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_column('receipts_due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipts_due_date', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
